### ISSUE TITLE
Not working with Anki 2.1.50 onward

### ISSUE THREAD

**Issue by WeberAlex** [cjhoward/anki-set-font-size#3]
This addon is not working with the newer version of Anki 2.1.51 (QT6), on Windows 11 & Linux Debian.

Error message:

```
When loading '⁨Set Font Size⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\a1010\AppData\Roaming\Anki2\addons21\651521808\__init__.py", line 41, in <module>
    changeFontSize()
  File "C:\Users\a1010\AppData\Roaming\Anki2\addons21\651521808\__init__.py", line 39, in changeFontSize
    changeWebFontSize()
  File "C:\Users\a1010\AppData\Roaming\Anki2\addons21\651521808\__init__.py", line 33, in changeWebFontSize
    wes = QWebEngineSettings.globalSettings()
  File "aqt.qt.qt5_compat", line 350, in __getattr__
AttributeError: type object 'QWebEngineSettings' has no attribute 'globalSettings'
```

A big thanks if you find the time the update it.

Set Font Size issue on [Anki forum](https://forums.ankiweb.net/t/set-font-size-2-1-50-error/19284)

**Comment by cjhoward** [comment]
Thanks for the feedback! The latest commit ([5080636](https://github.com/cjhoward/anki-set-font-size/commit/5080636e1e0fa03b5423be3f426767a5f3f31244)) should fix the issue. I've already updated the addon on AnkiWeb.
